"use strict";function*generateCycle(arr){let n=0;for(;;)yield arr[n],(n+=1)===arr.length&&(n=0)}const headers=generateCycle(["Whoops…","Oh well…","That’s life…","Don’t give up…","Almost there…"]);function renderFeedback(header,message){return`<h5>${header}</h5><p>${message}</p>`}function renderOutputLines(outputLines){return`<br /><code>${outputLines.replaceAll(/\n/g,"<br />")}</code>`}function getFeedback(outcome,expectedOutput){switch(outcome){case"pass":return saveCompletedExercise(EXERCISE_ID),renderFeedback("Well done! &#128077;","");case"fail":return renderFeedback(headers.next().value,`
        The output of your program doesn’t match the expected output.
        It should print: ${renderOutputLines(expectedOutput)}
      `);case"error":return renderFeedback(headers.next().value,`
        There’s an error in your code.
        Read the error message carefully and try to identify it!
      `);case"empty":return renderFeedback(headers.next().value,`
        Your program didn’t produce any output.
        It should print: ${renderOutputLines(expectedOutput)}
      `);default:return renderFeedback("Error","Sorry, an unexpected error occurred.")}}function runTest(stdout,stderr){var expectedOutput=document.querySelector("#output").textContent;let outcome;expectedOutput===stdout?.join("\n")?outcome="pass":0<stderr?.length?outcome="error":0<stdout?.length?outcome="fail":0===stdout?.length&&(outcome="empty"),document.querySelector("#feedback").innerHTML=getFeedback(outcome,expectedOutput)}window.addEventListener("load",()=>{"serviceWorker"in navigator?(navigator.serviceWorker.register("worker.min.js"),navigator.serviceWorker.addEventListener("message",event=>{runTest(event.data.logs?.stdout,event.data.logs?.stderr)})):document.querySelector("#content").innerHTML="<p>Sorry, this browser is not supported.</p>"});